nx = 1980
ny = 1080
ns = 100
thread_x = 8
thread_y = 8
max_reflect = 25

[camera]
aspect_ratio = 1.833333
vfov_degree = 90
aperture = 2    
pos.x = -2
pos.y = 2
pos.z = 1
lookAt.x = 0
lookAt.y = 0
lookAt.z = -1

[[object]]
    [object.shape]
        type = ST_SPHERE
        center = { x = 0, y = 0, z = -1 }
        radius = 0.5
    [object.material]
        type = MT_LAMBERTIAN       
        albedo = { x = 0.1, y = 0.2, z = 0.5 }
        
[[object]]
    [object.shape]
        type = ST_SPHERE
        center = { x = 0, y = -100.5, z = -1 }
        radius = 100
    [object.material]
        type = MT_LAMBERTIAN
        albedo = { x = 0.8, y = 0.8, z = 0.0 }

[[object]]
    [object.shape]
        type = ST_SPHERE
        center = { x = 1, y = 0, z = -1 }
        radius = 0.5
    [object.material]
        type = MT_METAL
        albedo = { x = 0.8, y = 0.6, z = 0.2 }
        fuzz = 0.5

[[object]]
    [object.shape]
        type = ST_SPHERE
        center = { x = -1, y = 0, z = -1 }
        radius = -0.49
    [object.material]
        type = MT_DIELECTRIC
        ref_idx = 1.5

[[object]]
    [object.shape]
        type = ST_SPHERE
        center = { x = -1, y = 0, z = -1 }
        radius = 0.5
    [object.material]
        type = MT_DIELECTRIC
        ref_idx = 1.5
